module SUME_ddr3_regs 
    import SUME_ddr3_pkg::*;
(
    // UI_CLK is the 189.39MHz clk generated by mig, 
    // needs to be used to interact with the MIG and 
    // passed on to the rest of the fpga to be used as system clock
    input logic UI_CLK,
    input logic UI_RESET,
    // logic of the soc
    axi_if.DEVICE axi,
    //ddr3_mig_if.CONTROLLER mem_if,

    input logic clk,
    input logic reset_n,
    //CDC signals out
    output logic en_o,

    output logic [2:0]  cmd_o,
    output logic [29:0] ddr3_addr_o,
    output logic [63:0] mask,
    output logic [(MIG_DATA_WIDTH-1):0] write_buffer_o,
    
    //CDC SIGNALS in
    input logic init_calib_complete_i,
    input logic ack_i,
    input logic rdata_we_i,
    input logic [(MIG_DATA_WIDTH-1):0] read_buffer_i
);

typedef enum logic [4:0] { 
    IDLE         = 5'b00001,
    WRITE_REQ    = 5'b00010,
    WRITE_ACK    = 5'b00100,
    READ_REQ     = 5'b01000,
    READ_ACK     = 5'b10000
    // READ_WAIT    = 8'b00100000,
    // READ_EN_FIFO = 8'b01000000,
    // READ_FIFO    = 8'b10000000
} states;

states current_state, next_state;

logic [31:0] axi_wdata;
logic [7:0] axi_addr_q;
logic [3:0] axi_wstrb;
logic axi_we, axi_re;

logic [(WDF_MASK_WIDTH)-1:0] wdf_mask_reg;

logic ddr3_addr_we;
logic [29:0] ddr3_addr_reg;

logic [MIG_DATA_WIDTH-1:0] read_buffer_reg;
logic read_buf_re;
logic [$clog2(BYTES_AMOUNT)-1:0] read_buffer_index;

logic data_avail;
logic [15:0] status_reg;
logic status_re;

logic command_we;
logic [15:0] command_reg;

logic write_buf_we;
logic [MIG_DATA_WIDTH-1:0] write_buffer_reg;
logic read_fifo_empty;

logic w_perf_count_re;
logic [15:0] w_perf_count;

logic r_ack_perf_count_re;
logic [15:0] r_ack_perf_count;
logic r_dlv_perf_count_re;
logic [15:0] r_dlv_perf_count;



always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        axi_we <= '0;
        axi_re <= '0;
        axi_addr_q <= '0;
        axi_wstrb <= '0;
        axi_wdata <='0;
    end else begin
        axi_we <= axi.awvalid;
        axi_re <= axi.arvalid;
        axi_wstrb <= axi.wstrb;
        if (axi.awvalid || axi.arvalid)
            axi_addr_q <= axi.awvalid ? axi.awaddr[7:0] : axi.araddr[7:0];

        if (axi.wvalid && axi.awvalid)
            axi_wdata <= axi.wdata[31:0];
    end
end
// axi response
assign axi.rvalid = axi_re;
assign axi.bvalid = axi_we;

assign axi.wready  = 1'b1;
assign axi.awready = 1'b1;
assign axi.arready = 1'b1;
assign axi.bresp   = '0;
assign axi.rresp   = '0;

logic read_op;
assign read_op = (command_reg[3:1] == CMD_READ);
logic write_op;
assign write_op = (command_reg[3:1] == CMD_WRITE);


always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        current_state <= IDLE;
    end else begin
        current_state <= next_state;
    end
end
logic ack_sync_r;
logic ack_sync_sync_1;
logic ack_sync_sync_2;
logic ack_trig;

always_ff@(posedge clk or negedge reset_n) begin // bring to slow clock domain
    if(!reset_n) begin
        ack_sync_sync_1 <= '0;
        ack_sync_sync_2 <= '0;
    end else begin
        ack_sync_sync_1 <= ack_i;
        ack_sync_sync_2 <= ack_sync_sync_1;
    end
end

always_ff@(posedge clk or negedge reset_n) begin // edge detecting
    if(!reset_n) begin
        ack_sync_r <= '0;
    end else begin
        ack_sync_r <= ack_sync_sync_2;
    end
end
assign ack_trig = (ack_sync_sync_2 && !ack_sync_r); //posedge ack

always_comb begin
    unique case(current_state) 
        IDLE: begin 
            if(command_reg[START_BIT]) begin
                if(read_op)
                    next_state = READ_REQ;
                else if(write_op)
                    next_state = WRITE_REQ;
                else
                    next_state = IDLE;
            end else begin
                next_state = IDLE;
            end
        end
        WRITE_REQ: begin // rise EN
            next_state = WRITE_ACK; 
        end
        WRITE_ACK: begin 
            if(ack_trig) // lower en
                next_state = IDLE; 
            else
                next_state = WRITE_ACK;
        end
        READ_REQ: begin
            next_state = READ_ACK;
        end
        READ_ACK: begin // rise en
            if(ack_trig)
                next_state = IDLE;
            else 
                next_state = READ_ACK;
        end
        // READ_WAIT: begin 
        //     if(!read_fifo_empty) // lower en
        //         next_state = READ_EN_FIFO; 
        //     else
        //         next_state =  READ_WAIT;
        // end
        // READ_EN_FIFO: begin
        //     next_state = READ_FIFO;
        // end
        // READ_FIFO: begin // rise rd_fifo and register it next cycle
        //     next_state = IDLE; 
        // end
        default: next_state = IDLE;
    endcase
end

logic en;
always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        en <= 'b0;
    end else begin
        unique case(current_state)
        WRITE_REQ,
        WRITE_ACK: en <= 1'b1;
        READ_REQ,
        READ_ACK: en <= 1'b1;
        default:  en <= 1'b0;
        endcase
    end
end



// WRITE DATA
logic buffer_en;
assign buffer_en = axi_addr_q[7];

logic rdbuf_en;
assign rdbuf_en = axi_addr_q[6];

logic [3:0] word_sel;
assign word_sel = axi_addr_q[5:2];

assign write_buf_we = axi_we && (buffer_en && !rdbuf_en);

logic [8:0] byte0;
logic [8:0] byte1;
logic [8:0] byte2;
logic [8:0] byte3;

assign byte0 = {word_sel, 2'b00, 3'b000};
assign byte1 = {word_sel, 2'b01, 3'b000};
assign byte2 = {word_sel, 2'b10, 3'b000};
assign byte3 = {word_sel, 2'b11, 3'b000};

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        write_buffer_reg <= '0;
    end else begin
        if(write_buf_we) begin
            if(axi_wstrb[0]) begin
                write_buffer_reg[byte0+:8] <= axi_wdata[7:0];
            end
            if(axi_wstrb[1]) begin
                write_buffer_reg[byte1+:8] <= axi_wdata[15:8];
            end
            if(axi_wstrb[2]) begin
                write_buffer_reg[byte2+:8] <= axi_wdata[23:16];
            end
            if(axi_wstrb[3]) begin
                write_buffer_reg[byte3+:8] <= axi_wdata[31:24];
            end
        end
    end
end

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        wdf_mask_reg <= '0;
    end else begin
        if(write_buf_we) begin
            // wdf mask is 0 for write, 1 for ignore, so invert write strobe
            wdf_mask_reg[byte0] <= !axi_wstrb[0];
            wdf_mask_reg[byte1] <= !axi_wstrb[1];
            wdf_mask_reg[byte2] <= !axi_wstrb[2];
            wdf_mask_reg[byte3] <= !axi_wstrb[3];
        end
    end
end


assign ddr3_addr_we = axi_we && (axi_addr_q == DDR3_ADDR);

always_ff@(posedge clk or negedge reset_n)begin
    if(!reset_n) begin
        ddr3_addr_reg <= '0;
    end else begin 
        if(ddr3_addr_we)
            ddr3_addr_reg <= axi_wdata;
    end
end

assign command_we = axi_we && (axi_addr_q == COMMAND_ADDR);

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        command_reg <= '0;
    end else begin
        if(command_we)
            command_reg <= axi_wdata;
        else if(command_reg[START_BIT] && current_state != IDLE)
            command_reg[START_BIT] <= 1'b0;
    end
end



// read buf

assign read_buf_re = axi_re && (buffer_en && rdbuf_en);

assign status_re = axi_re && (axi_addr_q == STATUS_ADDR);

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin 
        data_avail <='0;
    end else begin 
        if(!read_fifo_empty)
            data_avail <= 1'b1;
        else if (read_buf_re)
            data_avail <= 1'b0;
        else if (command_reg[START_BIT] && (cmd_o == CMD_READ))
            data_avail <= 1'b0;
    end
end

assign read_buffer_index = ($clog2(BYTES_AMOUNT))'(axi_addr_q - READ_BUFFER_ADDR_LOW);


logic init_calib_complete_sync1;
logic init_calib_complete_sync2;

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        init_calib_complete_sync1 <= '0;
        init_calib_complete_sync2 <= '0;
    end else begin 
        init_calib_complete_sync1 <= init_calib_complete_i;
        init_calib_complete_sync2 <= init_calib_complete_sync1;
    end
end
logic w_pending;
assign w_pending = (current_state == WRITE_ACK);
always_comb begin
    unique case(1'b1)
        read_buf_re: axi.rdata = read_buffer_reg[(read_buffer_index*8)+:32];
        status_re:   axi.rdata = 32'({'0,w_pending, data_avail, init_calib_complete_sync2});
        w_perf_count_re: axi.rdata = 32'({'0, w_perf_count});
        r_ack_perf_count_re: axi.rdata = 32'({'0, r_ack_perf_count});
        r_dlv_perf_count_re: axi.rdata = 32'({'0, r_dlv_perf_count});
        default: axi.rdata = 32'd0;
    endcase
end

logic [MIG_DATA_WIDTH-1:0] read_fifo_data_o;
logic read_en_fifo;

DATA_FIFO u_read_fifo (
  .rst(!reset_n),               // input wire rst
  .wr_clk(UI_CLK),         // input wire wr_clk
  .rd_clk(clk),         // input wire rd_clk
  .din(read_buffer_i),     // input wire [511 : 0] din
  .wr_en(rdata_we_i),      // input wire wr_en
  .rd_en(read_en_fifo),    // input wire rd_en
  .dout(read_fifo_data_o), // output wire [511 : 0] dout
  .full(full),             // output wire full
  .empty(read_fifo_empty)  // output wire empty
);

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        read_en_fifo  <='0;
    end else begin
        if(!read_fifo_empty) begin
            read_en_fifo <= 1'b1;
        end else begin
            read_en_fifo <= 1'b0;
        end
    end
end



always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        read_buffer_reg <= '0;
    end else begin
        if(read_en_fifo)
            read_buffer_reg <= read_fifo_data_o;
    end
end

assign cmd_o = command_reg[3:1];
assign en_o = en;
assign ddr3_addr_o = ddr3_addr_reg;
assign mask = wdf_mask_reg;
assign write_buffer_o = write_buffer_reg;


// perf counters

assign w_perf_count_re = axi_re && (axi_addr_q == W_PERF_COUNT_ADDR);

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        w_perf_count <= '0;
    end else begin
        if(current_state == WRITE_REQ)
            w_perf_count <= '0;
        else if(current_state == WRITE_ACK)
            w_perf_count <= w_perf_count + 1'b1;
    end
end


assign r_ack_perf_count_re = axi_re && (axi_addr_q == R_ACK_PERF_COUNT_ADDR);

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        r_ack_perf_count <= '0;
    end else begin
        if(current_state == READ_REQ)
            r_ack_perf_count <= '0;
        else if(current_state == READ_ACK)
            r_ack_perf_count <= r_ack_perf_count + 1'b1;
    end
end

assign r_dlv_perf_count_re = axi_re && (axi_addr_q == R_DLV_PERF_COUNT_ADDR);

always_ff@(posedge clk or negedge reset_n) begin
    if(!reset_n) begin
        r_dlv_perf_count <= '0;
    end else begin
        if(current_state == READ_REQ)
            r_dlv_perf_count <= '0;
        else if(!data_avail)
            r_dlv_perf_count <= r_dlv_perf_count + 1;
    end
end





ila_0 your_instance_name (
	.clk(clk), // input wire clk


	.probe0(axi_wdata), // input wire [31:0]  probe0  
	.probe1(axi_we), // input wire [0:0]  probe1 
	.probe2(write_buffer_reg[31:0]), // input wire [31:0]  probe2 
	.probe3(write_buf_we), // input wire [0:0]  probe3 
	.probe4(byte0), // input wire [8:0]  probe4 
	.probe5(byte1), // input wire [8:0]  probe5 
	.probe6(byte2), // input wire [8:0]  probe6 
	.probe7(byte3), // input wire [8:0]  probe7 
	.probe8(axi_addr_q), // input wire [7:0]  probe8 
	.probe9(command_reg[3:1]), // input wire [2:0]  probe9 
	.probe10(command_we), // input wire [0:0]  probe10 
	.probe11(command_reg), // input wire [15:0]  probe11 
	.probe12(init_calib_complete_sync2), // input wire [0:0]  probe12 
	.probe13(read_fifo_empty), // input wire [0:0]  probe13 
	.probe14(read_fifo_data_o[31:0]), // input wire [31:0]  probe14 
	.probe15(current_state), // input wire [4:0]  probe15 
	.probe16(en), // input wire [0:0]  probe16 
	.probe17(ack_trig), // input wire [0:0]  probe17 
	.probe18(axi_re), // input wire [0:0]  probe18
    .probe19(read_buffer_reg[31:0]), // input wire [31:0]  probe19 
	.probe20(read_en_fifo), // input wire [0:0]  probe20
    .probe21(r_dlv_perf_count), // input wire [15:0]  probe21 
	.probe22(r_dlv_perf_count_re), // input wire [0:0]  probe22 
	.probe23(r_ack_perf_count), // input wire [15:0]  probe23 
	.probe24(r_ack_perf_count_re), // input wire [0:0]  probe24 
	.probe25(w_perf_count), // input wire [15:0]  probe25 
	.probe26(w_perf_count_re) // input wire [0:0]  probe26
);


endmodule
