#!/usr/bin/env python3
"""
prepare_fc_inputs.py
--------------------
Generates data/*.h header files for the AlexNet FC layers (FC6, FC7, FC8).

Weights are loaded from the pretrained torchvision AlexNet model and quantized
to fixed-point integers using the same Q10 scheme as the convolutional layers:
    int_value = round(float_value * 1024)

The FC6 input (in_fc6.h, the real Conv5 output) is generated by prepare_inputs.py.
"""

import os
import numpy as np
import torch
import torchvision.models as models

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR   = os.path.join(SCRIPT_DIR, "data")
os.makedirs(DATA_DIR, exist_ok=True)

SCALE = 1024   # Q10 fixed-point: 1.0 → 1024

# ---------------------------------------------------------------------------
# Load pretrained AlexNet
# ---------------------------------------------------------------------------
print("Loading pretrained AlexNet weights...")
alexnet = models.alexnet(weights=models.AlexNet_Weights.DEFAULT)
alexnet.eval()

# Classifier indices:
#   classifier[0]  Dropout
#   classifier[1]  Linear(9216 -> 4096)  ← FC6
#   classifier[2]  ReLU
#   classifier[3]  Dropout
#   classifier[4]  Linear(4096 -> 4096)  ← FC7
#   classifier[5]  ReLU
#   classifier[6]  Linear(4096 -> 1000)  ← FC8
fc6 = alexnet.classifier[1]
fc7 = alexnet.classifier[4]
fc8 = alexnet.classifier[6]

def to_q10(tensor):
    """Convert float tensor to Q10 fixed-point int array (numpy)."""
    return np.round(tensor.detach().numpy() * SCALE).astype(np.int32)

w6 = to_q10(fc6.weight)   # (4096, 9216)
b6 = to_q10(fc6.bias)     # (4096,)
w7 = to_q10(fc7.weight)   # (4096, 4096)
b7 = to_q10(fc7.bias)     # (4096,)
w8 = to_q10(fc8.weight)   # (1000, 4096)
b8 = to_q10(fc8.bias)     # (1000,)

print(f"  FC6 weights : {w6.shape}  range [{w6.min()}, {w6.max()}]")
print(f"  FC7 weights : {w7.shape}  range [{w7.min()}, {w7.max()}]")
print(f"  FC8 weights : {w8.shape}  range [{w8.min()}, {w8.max()}]")

# ---------------------------------------------------------------------------
# Helper: write a C header file
# ---------------------------------------------------------------------------
def write_header(path, guard, decl_type, name, data, comment=""):
    flat = data.flatten()
    vals_per_line = 10
    lines = []
    lines.append(f"/* Auto-generated by prepare_fc_inputs.py — do not edit */")
    if comment:
        lines.append(f"/* {comment} */")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"static const {decl_type} {name}[{flat.size}] = {{")
    for i in range(0, flat.size, vals_per_line):
        chunk = flat[i:i + vals_per_line]
        row   = ", ".join(str(v) for v in chunk)
        suffix = "," if (i + vals_per_line) < flat.size else ""
        lines.append(f"{row}{suffix}")
    lines.append("};")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    kb = flat.size * 4 / 1024
    print(f"  Wrote {os.path.basename(path)}  ({flat.size} values, {kb:.1f} KiB)")

# ---------------------------------------------------------------------------
# Write header files
# ---------------------------------------------------------------------------
print("\nWriting header files...")

write_header(
    os.path.join(DATA_DIR, "weights_fc6.h"),
    "WEIGHTS_FC6_H", "int", "weights_fc6", w6,
    "FC6 weights: 4096 x 9216 = 37748736 values (Q10 quantized)")

write_header(
    os.path.join(DATA_DIR, "bias_fc6.h"),
    "BIAS_FC6_H", "int", "bias_fc6", b6,
    "FC6 biases: 4096 values (Q10 quantized)")

write_header(
    os.path.join(DATA_DIR, "weights_fc7.h"),
    "WEIGHTS_FC7_H", "int", "weights_fc7", w7,
    "FC7 weights: 4096 x 4096 = 16777216 values (Q10 quantized)")

write_header(
    os.path.join(DATA_DIR, "bias_fc7.h"),
    "BIAS_FC7_H", "int", "bias_fc7", b7,
    "FC7 biases: 4096 values (Q10 quantized)")

write_header(
    os.path.join(DATA_DIR, "weights_fc8.h"),
    "WEIGHTS_FC8_H", "int", "weights_fc8", w8,
    "FC8 weights: 1000 x 4096 = 4096000 values (Q10 quantized)")

write_header(
    os.path.join(DATA_DIR, "bias_fc8.h"),
    "BIAS_FC8_H", "int", "bias_fc8", b8,
    "FC8 biases: 1000 values (Q10 quantized)")

total_mb = (w6.size + w7.size + w8.size + b6.size + b7.size + b8.size) * 4 / 1024**2
print(f"\nDone. Total data size: {total_mb:.1f} MiB")
print("Make sure MEM_SIZE in fc/Makefile is large enough (currently 512 MiB).")
