#!/usr/bin/env python3
"""
prepare_inputs.py
-----------------
Generates data/*.h for the AlexNet conv layers from the Memphis cnn5 application,
so that the per-layer RS5 runs use exactly the same data as the Memphis experiments.

Copied from cnn5 (per-PE slices are reassembled into full tensors in the order
cnn5 applies them, see the note in main()):
    input_1.h               <- p1_0_in.h .. p1_2_in.h
    weights_1.h .. 5.h      <- p1_*/p3_*/p5_*/p7_*/p9_*_weights.h
    bias_1.h .. 5.h         <- p2/p4/p6/p8/p10_bias.h

Computed by running the network in integer arithmetic identical to cnn_common.h
(int32 accumulate, (sum + bias) / 1024 truncating toward zero, ReLU, MaxPool):
    in_layer2.h  conv1 -> ReLU -> MaxPool    [64][27][27]
    in_layer3.h  conv2 -> ReLU -> MaxPool    [192][13][13]
    in_layer4.h  conv3 -> ReLU               [384][13][13]
    in_layer5.h  conv4 -> ReLU               [256][13][13]
    in_fc6.h     conv5 -> ReLU -> MaxPool    [256][6][6] = 9216

Usage:
    python3 prepare_inputs.py [path/to/memphis/applications/cnn5]
"""

import os
import re
import sys
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR   = os.path.join(SCRIPT_DIR, "data")
CNN5_DIR   = sys.argv[1] if len(sys.argv) > 1 else "/sim/williann/Jetc/scalar/applications/cnn5"

# (out_ch, in_ch, kernel, stride, pad, n_pes, weights task, bias task)
LAYERS = [
    ( 64,   3, 11, 4, 0, 3, "p1", "p2"),
    (192,  64,  5, 1, 2, 8, "p3", "p4"),
    (384, 192,  3, 1, 1, 4, "p5", "p6"),
    (256, 384,  3, 1, 1, 6, "p7", "p8"),
    (256, 256,  3, 1, 1, 4, "p9", "p10"),
]
POOL_AFTER = {1: True, 2: True, 3: False, 4: False, 5: True}  # 3x3 maxpool, stride 2


def load(path):
    s = open(path).read()
    s = s[s.index("{") + 1:s.rindex("}")]
    return np.array([int(x) for x in re.findall(r"-?\d+", s)], dtype=np.int64)


def write_header(name, data, comment):
    flat = data.ravel()
    path = os.path.join(DATA_DIR, f"{name}.h")
    guard = f"{name.upper()}_H"
    with open(path, "w") as f:
        f.write("/* Auto-generated by prepare_inputs.py — do not edit */\n")
        f.write(f"/* {comment} */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(f"static const int {name}[{flat.size}] = {{\n")
        for i in range(0, flat.size, 10):
            f.write(", ".join(str(v) for v in flat[i:i + 10]))
            f.write(",\n" if i + 10 < flat.size else "\n")
        f.write("};\n\n#endif\n")
    print(f"  {name:12s} {flat.size:7d} values -> {path}")


def wrap32(x):
    return ((x + 2**31) % 2**32) - 2**31


def conv(x, w, b, stride, pad):
    """Integer conv matching conv_channel + conv_sum_bias in cnn_common.h."""
    if pad:
        x = np.pad(x, ((0, 0), (pad, pad), (pad, pad)))
    c, h, _ = x.shape
    o, _, k, _ = w.shape
    oh = (h - k) // stride + 1
    # im2col: [c*k*k, oh*oh]
    cols = np.empty((c, k, k, oh, oh), dtype=np.int64)
    for fy in range(k):
        for fx in range(k):
            cols[:, fy, fx] = x[:, fy:fy + stride * oh:stride, fx:fx + stride * oh:stride]
    acc = w.reshape(o, -1) @ cols.reshape(c * k * k, -1)
    if np.abs(acc).max() >= 2**31:
        print("  WARNING: accumulator exceeds int32, wrapping like C would")
    acc = wrap32(wrap32(acc) + b[:, None])
    out = np.sign(acc) * (np.abs(acc) // 1024)   # C integer division truncates toward zero
    return out.reshape(o, oh, oh)


def maxpool(x, size=3, stride=2):
    c, h, _ = x.shape
    oh = (h - size) // stride + 1
    out = np.zeros((c, oh, oh), dtype=np.int64)  # max starts at 0, as in cnn_common.h
    for wy in range(size):
        for wx in range(size):
            out = np.maximum(out, x[:, wy:wy + stride * oh:stride, wx:wx + stride * oh:stride])
    return out


def main():
    os.makedirs(DATA_DIR, exist_ok=True)
    print(f"Reading cnn5 data from {CNN5_DIR}")

    x = np.concatenate([load(f"{CNN5_DIR}/p1_{p}_in.h") for p in range(3)]).reshape(3, 227, 227)
    write_header("in_1", x, "Input image [3][227][227], from cnn5 p1_*_in.h")
    os.replace(os.path.join(DATA_DIR, "in_1.h"), os.path.join(DATA_DIR, "input_1.h"))

    outputs = {1: "in_layer2", 2: "in_layer3", 3: "in_layer4", 4: "in_layer5", 5: "in_fc6"}
    for n, (o, i, k, stride, pad, n_pes, wt, bt) in enumerate(LAYERS, start=1):
        il = i // n_pes
        pe = [load(f"{CNN5_DIR}/{wt}_{p}_weights.h").reshape(o, il, k, k) for p in range(n_pes)]
        # cnn5 distributes input channels round-robin (channel c -> PE c % n_pes, as its
        # local channel c / n_pes), while each PE's weight file holds a contiguous block
        # of channels. Rebuild the weights as cnn5 effectively applies them.
        w = np.stack([pe[c % n_pes][:, c // n_pes] for c in range(i)], axis=1)
        b = load(f"{CNN5_DIR}/{bt}_bias.h")
        assert b.size == o
        write_header(f"weights_{n}", w, f"Conv{n} weights [{o}][{i}][{k}][{k}], from cnn5 {wt}_*_weights.h")
        write_header(f"bias_{n}", b, f"Conv{n} bias [{o}], from cnn5 {bt}_bias.h")

        x = np.maximum(conv(x, w, b, stride, pad), 0)
        if POOL_AFTER[n]:
            x = maxpool(x)
        write_header(outputs[n], x, f"Output of conv{n} ({'ReLU + MaxPool' if POOL_AFTER[n] else 'ReLU'}) {list(x.shape)}")


if __name__ == "__main__":
    main()
